webapp:
  build: .
  name: riauditor
  container_name: riauditor_webapp
  working_dir: /home/app/webapp
  ports:
    - "80"
  env_file:
    - .env
    - .env.webapp
  volumes:
    - .:/home/app/webapp
